// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfkqoMZ0zEs2srUJG7fWdZXBIAi5JjY3o',
    appId: '1:983337077015:web:2a7c0262f8ef0df22d4f52',
    messagingSenderId: '983337077015',
    projectId: 'tager-ee368',
    authDomain: 'tager-ee368.firebaseapp.com',
    storageBucket: 'tager-ee368.appspot.com',
    measurementId: 'G-ZZG0NL7CL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVcokng7UAoA7R8oi7GtBrh0vOciYrO0',
    appId: '1:983337077015:android:f3c9f6299cf207372d4f52',
    messagingSenderId: '983337077015',
    projectId: 'tager-ee368',
    storageBucket: 'tager-ee368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVuEoDLwlBTvaJ0chmBeC8ENR_LMZlmc',
    appId: '1:983337077015:ios:59cd2f02a44f123e2d4f52',
    messagingSenderId: '983337077015',
    projectId: 'tager-ee368',
    storageBucket: 'tager-ee368.appspot.com',
    iosBundleId: 'com.tager.tager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVuEoDLwlBTvaJ0chmBeC8ENR_LMZlmc',
    appId: '1:983337077015:ios:f6bdb9abb56786c62d4f52',
    messagingSenderId: '983337077015',
    projectId: 'tager-ee368',
    storageBucket: 'tager-ee368.appspot.com',
    iosBundleId: 'com.tager.tager.RunnerTests',
  );
}
